# Agent global
[agent]
  interval = "30s"            # fréquence de collecte
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""
  hostname = "telegraf_subscriber"
  omit_hostname = false

# ===========================
#   INPUT MQTT CONSUMER
# ===========================
[[inputs.mqtt_consumer]]
  servers = ["ssl://128f659d3e694c8ea95298fc0285627f.s1.eu.hivemq.cloud:8883"]
  topics = ["solarwind/30s", "solarwind/1h"]
  username = "esp_32_solarwind"
  password = "M10u3b4i5n6e7."
  qos = 1
  client_id = "telegraf_subscriber"
  data_format = "json"

# ===========================
#   OUTPUT INFLUXDB CLOUD
# ===========================
[[outputs.influxdb_v2]]
  urls = ["https://us-east-1-1.aws.cloud2.influxdata.com"]
  token = "9S4F0G8g7pykaFx5xPdZBiuVEH41BUOU7xiD7wr-ZV8rHwF79wlQ3fZXJzrp6Ls5CFc00QhOKmrCtRhLEZPYyg=="
  organization = "solarwind"
  bucket = "solarwind_data"
